apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  releaseName: sonarqube
  chart:
    spec:
      chart: ./clusters/minikube/sonarqube-chart
      sourceRef:
        kind: GitRepository
        name: flux-system
  interval: 5m
  values:
    # You can override values.yaml here if needed
    nodeSelector:
      deploy: "true"
