apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sonarqube
  namespace: flux-system
spec:
  interval: 5m
  path: ./cluster/minikube/sonarqube
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: sonarqube
